version: '3.9'
services:
  javalin-template:
    image: javalin-template:latest
    container_name: javalin-template
    hostname: docker-local
    env_file:
      - config/service.env
      - config/otel.env
      #      - config/otel-collect-nr.env
      - config/otel-collect-oss.env
    environment:
      TZ: "America/Chicago"
    ports:
      - "10001:10000"
    networks:
      - develop-bridge-network
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G

networks:
  develop-bridge-network:
    name: develop-bridge
    external: true