name: Maven Docker Push

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  push_to_registry:
    name: Push docker image to docker hub
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Create local settings.xml file
      uses: s4u/maven-settings-action@v2.8.0
      with:
        servers: |
          [{
            "id": "docker.io",
            "username": "${{ secrets.DOCKERHUB_USERNAME }}",
            "password": "${{ secrets.DOCKERHUB_PASSWORD }}"
          }]
          
    - name: Build with Maven
      run: mvn install
